version: "3.8"
services:
  # Nginx servers
  nginx-backend:
    image: nginx
    container_name: tingeso-alan-nginx-backend-container
    restart: always
    ports:
      - 80:80
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - tingeso-alan-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3      
  nginx-frontend:
    image: nginx
    container_name: tingeso-alan-nginx-frontend-container
    restart: always
    ports:
      - 8070:8070
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - tingeso-alan-frontend-network
    depends_on:      
      - react1
      - react2
      - react3
  mysql:
    container_name: tingeso-alan-mysql-container
    image: mysql
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - tingeso-alan-mysql-volume:/var/lib/mysqlql/data
    networks:
      - tingeso-alan-backend-network
    environment:      
      mysql_PASSWORD: mysql
    ports:
      - 5435:3306      
  spring1:
    container_name: tingeso-alan-backend-container-1
    image: alanberrios/tingeso-alan-backend
    ports:
      - 8091:8090
    environment:
      DB_HOST: tingeso-alan-mysql-container
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: 1234
    networks:
      - tingeso-alan-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring2:
    container_name: tingeso-alan-backend-container-2
    image: alanberrios/tingeso-alan-backend
    ports:
      - 8092:8090
    environment:
      DB_HOST: tingeso-alan-mysql-container
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
    networks:
      - tingeso-alan-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
  spring3:
    container_name: tingeso-alan-backend-container-3
    image: alanberrios/tingeso-alan-backend
    ports:
      - 8093:8090
    environment:
      DB_HOST: tingeso-alan-mysql-container
      DB_PORT: 3306
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
    networks:
      - tingeso-alan-backend-network
    deploy:
      restart_policy:
        condition: on-failure
  react1:
    container_name: tingeso-alan-frontend-container-1
    image: alanberrios/tingeso-alan-frontend
    ports:
      - 3001:3000
    networks:
      - tingeso-alan-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: tingeso-alan-frontend-container-2
    image: alanberrios/tingeso-alan-frontend
    ports:
      - 3002:3000
    networks:
      - tingeso-alan-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: tingeso-alan-frontend-container-3
    image: alanberrios/tingeso-alan-frontend
    networks:
      - tingeso-alan-frontend-network
    ports:
      - 3003:3000
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  tingeso-alan-mysql-volume:
networks:
  tingeso-alan-frontend-network:
  tingeso-alan-backend-network: